<ul>
<li><a href="http://www.scriptol.fr/programmation/rust.php">Rust, le verlan des langages de programmation</a><br>  Conçu par Mozilla pour réaliser un nouveau navigateur, "Servo", le langage Rust disponible sur Github intéresse les programmeurs système qui y voient un successeur possible à C  dans leur domaine.</li>
<li><a href="http://www.scriptol.fr/seo/panda-en-clair.php">Le brevet Panda en clair</a><br>Description simplifiée du brevet 8,682,892 de classement des pages, images et autres ressources, supposé pénaliser les sites de pauvre qualité, et principalement les fermes de contenu.</li>
<li><a href="http://www.scriptol.fr/technologies/intel-nuc-D54250WYKH2-test.php">Intel NUC: montage, performances et utilisation</a><br>Le modèle D5425WYKH passé en revue, du montage à l'utilisation.</li>
<li><a href="http://www.scriptol.fr/logiciel/licences.php">Quelle licence pour mon logiciel open source?</a><br>Les règles et permissions définies dans les licences logicielles open source les plus fréquemment utilisées.</li>
<li><a href="http://www.scriptol.fr/programmation/julia.php">Julia vs Python</a><br>Julia est un challenger à Python dans le domaine scientifique, chacun disposant d'une bibliothèque étendue. Le nouveau venu peut-il remplacer l'ancien? (Python date de 1991).</li>
<li><a href="http://www.scriptol.fr/programmation/csharp.php">C#, le Java de Microsoft</a><br> Le langage C# est plus facile d'emploi que C , mais il requiert le runtime de .NET pour faire tourner les programmes. Vous pouvez convertir votre code C sans difficulté. C# a été conçu par Microsoft pour sa nouvelle plateforme .</li>
<li><a href="http://www.scriptol.fr/seo/panda-update.php">Comprendre l'algorithme Panda de Google </a><br>La modification du classement des pages par Google du 24 février 2011, qui prend le nom de l'ingénieur qui l'a dirigée, a impactée 11,8% des sites aux USA en réduisant la présence dans les résultats de pages au contenu jugé pauvre, non original ou peu</li>
<li><a href="http://www.scriptol.fr/compilateur/mante.php">Au-delà des langages de programmation cabalistiques...</a><br>Suis-je le seul à trouver que ces crochets et autres symboles cabalistiques sont plutôt aggressifs?</li>
<li><a href="http://www.scriptol.fr/xml/applications-svg.php">Que peut-on faire avec SVG?</a><br>Les meilleures applications actuelles réalisées avec SVG vous ferons voir ce que l'on peut faire avec ce langage graphique standard.</li>
<li><a href="http://www.scriptol.fr/web/steve-jobs-secret.php">Le secret d'Apple par Steve Jobs lui-même </a><br>Le secret d'Apple a fait l'objet d'une longue étude par John Sculley. Voici maintenant ce que Steve Jobs lui-même a dit concernant le succès de la firme.</li>
<li><a href="http://www.scriptol.fr/programmation/citations.php">Citations sur les langages de programmation</a><br>Ce que les informaticiens, les auteurs et programmeurs pensent des langages de programmation populaires. Tous les langages Algol 60 (Repris dans C) "Je ne pouvais pas résister à la tentation de mettre une référence nulle, simplement parce que c'étai</li>
<li><a href="http://www.scriptol.fr/mobile/native-vs-html5.php">Programmation mobile: Native vs HTML 5 vs Titanium</a><br>Quel plateforme choisir? Les avantages et inconvénients en considérant tous les aspects de la programmation.</li>
<li><a href="http://www.scriptol.fr/css/checkbox.php">Case à cocher professionnelles sans framework</a><br>Avec une feuille de style CSS et une fonction JavaScript, vos formulaires changent de look. En fait on peut le réaliser uniquement avec du code CSS et JavaScript, en utilisant l'élément de formulaire standard <button> plutôt que <checkbox>.</li>
<li><a href="http://www.scriptol.fr/html5/formulaire.php">Tous les objets de formulaire en HTML 5</a><br>HTML 5 permet de réaliser des interfaces utilisateurs complètes grâce à un ensemble de widgets plus étendus, objets de formulaire et éléments interactifs. La prévisualisation permet de vérifier directement la compatibilité avec chaque navigateur</li>
</ul>

